### ISSUE TITLE
how can i get the code in this submodule

### ISSUE THREAD

**Issue by zorroe** [danmox/learning-connectivity#3]
After I use command `git clone --recursive https://github.com/danmox/learning-connectivity.git`, the content below this submodule seems to be empty,how can i get the code in this submodule,**Thanks**
![image](https://user-images.githubusercontent.com/53567817/160128721-cafa7feb-15bd-4bb7-aa3f-5ca9fbd8eccd.png)

**Comment by danmox** [comment]
Hi @LiXuuuu, I have removed the submodule since it pointed to a non-public repo (whoops!) and added the dependencies. You should be able to clone the repo now.
